export const workVisaData = [

  /* ─────────────────────────────────────────
     1. ALBANIA
  ───────────────────────────────────────── */
  {
    id: "albania",
    country: "Albania",
    region: "Europe",
    visaType: "E-Visa",
    category: "Work Permit",
    processingTime: "Approximately 100–157 working days (4–6 months)",
    salary: "€540 – €1,080/month depending on role",
    workHours: "180 hours/month (8 hrs/day, 5–6 days/week)",
    benefits: [
      "Free or subsidized shared accommodation (availability varies by employer and location)",
      "Transportation to and from the workplace or monthly transportation allowance",
      "Work clothing and occupational safety gear for relevant job roles",
      "Occupational health care in compliance with Albanian regulations",
      "Paid public holidays and annual leave as per Albanian labor law",
      "Mandatory work accident insurance coverage",
      "Airline ticket for initial travel to Albania (subject to employer policy)",
    ],
    whyChoose: [
      "Albania has a much easier and less competitive work visa process compared to other European countries.",
      "A fast-growing economy with opportunities in agriculture, energy, textiles, hospitality, and construction.",
      "Employer provides accommodation, meals, and transport — your expenses are minimal.",
      "Excellent natural beauty and UNESCO heritage sites make Albania a wonderful place to live.",
      "Albania serves as a strong springboard for future career opportunities in other European nations.",
    ],
    inDemandJobs: [
      { title: "Electrician (Skilled)", gender: "Male & Female", age: "18+", salary: "€800 – €1,080/month | €4.44–€6.00/hr", note: "5–6 days/week. Installation & maintenance." },
      { title: "Construction Worker (Semi-Skilled)", gender: "Male only", age: "18+", salary: "€540 – €720/month | €3.00–€4.00/hr", note: "5–6 days/week. Project-based work." },
      { title: "Plumber (Skilled)", gender: "Male only", age: "18+", salary: "€720 – €1,000/month | €4.00–€5.56/hr", note: "5–6 days/week. Plumbing systems." },
      { title: "Warehouse Worker (Semi-Skilled)", gender: "Male & Female", age: "18+", salary: "€700 – €790/month | €3.89–€4.39/hr", note: "5–6 days/week. Loading & inventory." },
      { title: "Fruit Packing Staff (Non-Skilled)", gender: "Male & Female", age: "18+", salary: "€630 – €680/month | €3.50–€3.78/hr", note: "5–6 days/week. Sorting & packing." },
    ],
    salaryTable: [
      { hours: "Electrician (Skilled)", monthly: "€800 – €1,080", annual: "€4.44 – €6.00/hr" },
      { hours: "Construction Worker", monthly: "€540 – €720", annual: "€3.00 – €4.00/hr" },
      { hours: "Plumber (Skilled)", monthly: "€720 – €1,000", annual: "€4.00 – €5.56/hr" },
      { hours: "Warehouse Worker", monthly: "€700 – €790", annual: "€3.89 – €4.39/hr" },
      { hours: "Fruit Packing Staff", monthly: "€630 – €680", annual: "€3.50 – €3.78/hr" },
    ],
    requirements: [
      "Valid passport (all pages copy)",
      "Albania visa photo — 35x45mm size",
      "Educational certificate, diploma, or professional qualification (matching the applied role)",
      "Work experience certificate from previous employer (if applicable)",
      "English language proficiency — B1 level may be required depending on employer and role",
      "Mandatory pre-employment medical examination prior to visa issuance and deployment",
    ],
    permitTypes: [
      { type: "Type A – General Employment", for: "Regular workers, seasonal labourers, students" },
      { type: "Type B – Self-Employment", for: "Business owners and investors" },
      { type: "Type C – Special Projects", for: "Specific sector or project-based work" },
      { type: "Type D – Long-term Employment", for: "Long-term or permanent employment permit" },
    ],
    workProcess: [
      "Document Verification: Screening and validation of candidate documentation — 10–15 working days",
      "Employer Submission: Job offer and employment contract submission to Albanian authorities — 10–20 working days",
      "Work Permit Processing: Review and approval by Albanian immigration authorities — 60–90 working days",
      "Residence Permit Decision: Biometrics appointment and final approval — 10–15 working days",
      "Pre-Departure Training: Orientation, safety instruction, and cultural briefing — 5–7 working days",
      "Travel & Deployment: Flight arrangements and onboarding — 5–10 working days",
    ],
    accommodation: "Shared rooms (2–4 persons). Furnished. Shared kitchen and bathroom. No family, partners, or pets. Some employers offer single rooms for married couples.",
    eligibleNationalities: ["All nationalities — open applications"],
    important: "Employment Contract Duration: Minimum 2 years (renewable). Probation Period: 3–6 months. Total Estimated Processing Time: Approximately 100–157 working days (around 4–6 months).",
  },

  /* ─────────────────────────────────────────
     2. DENMARK
  ───────────────────────────────────────── */
  {
    id: "denmark",
    country: "Denmark",
    
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "117–137 Working Days",
    salary: "€2,100 – €3,500/month depending on role",
    workHours: "8 hrs/day, 5–6 days/week",
    benefits: [
      "Accommodation provided by company",
      "Food allowance or subsidized meals",
      "Health insurance provided as per Danish standards",
      "Daily transportation to/from workplace",
      "PPE safety equipment for Construction & Welder positions",
      "Duty hours, leave, and overtime follow Danish labor regulations",
    ],
    whyChoose: [
      "Denmark offers some of the highest wages in Europe with strong worker protections.",
      "Stable work environment with guaranteed salary and legal compliance.",
      "Accommodation, meals, transport and PPE all provided by employer.",
      "Excellent public services and quality of life.",
      "SNJ GlobalRoutes provides complete end-to-end support for your work permit and visa application.",
    ],
    inDemandJobs: [
      { title: "Packing Worker", gender: "Male & Female", age: "18+", salary: "€2,100/month", note: "40 vacancies. 8 hrs/day, 6 days/week." },
      { title: "Warehouse Worker", gender: "Male & Female", age: "18+", salary: "€2,100/month", note: "38 vacancies. 8 hrs/day, 5 days/week." },
      { title: "Construction Worker (Skilled & Non-Skilled)", gender: "Male only", age: "18+", salary: "€2,500 – €3,500/month", note: "50 vacancies. 8 hrs/day, 6 days/week. Safety Certificates & Experience Letters required." },
      { title: "Welder (Minimum 5G Certified)", gender: "Male only", age: "18+", salary: "€2,800/month", note: "13 vacancies. 8 hrs/day, 5 days/week. Technical Certificates & Experience Letters required." },
    ],
    requirements: [
      "Passport PDF Copy",
      "Passport Size Photo",
      "Updated CV / Resume",
      "Safety Certificates (Construction Worker)",
      "Experience Letters (Construction & Welder roles)",
      "Technical Certificates (Welder 5G)",
    ],
    permitTypes: [
      { type: "Standard Work Permit", for: "Contract-based employment with Danish employer" },
      { type: "Skilled Worker Permit", for: "Certified and experienced professionals" },
      { type: "Seasonal Work Permit", for: "Agriculture, tourism, packing roles" },
      { type: "EU Blue Card", for: "Highly qualified professionals" },
    ],
    workProcess: [
      "Document Verification: Verification of passport, CV, certifications — 7 working days",
      "Job Offer Issuance: Preparation and issuance of official job offer — 20–25 working days",
      "Work Permit & Approval: Government approval and work permit processing — 60–75 working days",
      "Pre-departure Training: Orientation and safety training — 15 working days",
      "Travel & Deployment: Ticketing, coordination, and deployment — 15 working days",
    ],
    accommodation: "Provided by company. Shared rooms. No family, partners, or pets.",
    eligibleNationalities: ["All nationalities — contact us for eligibility confirmation"],
    important: "Salaries are paid monthly in EURO (€), convertible to DKK upon arrival. Any violation of company rules may result in termination as per Danish law. Employees must maintain valid work permits and visas at all times.",
  },

  /* ─────────────────────────────────────────
     3. FINLAND
  ───────────────────────────────────────── */
  {
    id: "finland",
    country: "Finland",
    flag: "🇫🇮",
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "125–165 Working Days",
    salary: "€1,800 – €2,700/month depending on role",
    workHours: "40 hours/week (as per Finnish Working Hours Act)",
    benefits: [
      "Free Shared Accommodation (as per Finland employer agreement)",
      "Transportation to and from workplace",
      "Health Insurance as per Finnish Employment Law",
      "Food Allowance / Meals (job-specific)",
      "Personal Protective Equipment (PPE) for industrial roles",
      "Paid Annual Leave (per Finnish Labor Law, minimum 2.5 days/month)",
      "Sick Leave Benefits (as per Finland Social Insurance Institution – KELA)",
      "Safe and compliant working environment following Finland Occupational Safety Guidelines",
    ],
    whyChoose: [
      "Finland offers some of the best worker protections in the world with collective bargaining agreements guaranteeing fair wages.",
      "Average monthly salaries of €1,800–€2,700 — significantly higher than most European countries.",
      "Employer provides accommodation, transport, health insurance, and meals.",
      "Minimum 2.5 paid leave days per month guaranteed by Finnish Labor Law.",
      "Sick leave benefits provided via Finland's Social Insurance Institution (KELA).",
    ],
    inDemandJobs: [
      { title: "Packaging / Warehouse Worker", gender: "Male & Female", age: "18+", salary: "€1,800 – €2,400/month | €11.5–€14.5/hr", note: "5 days/week, shift work common. ~8 hrs/day." },
      { title: "Store Keeper / Retail Worker", gender: "Male & Female", age: "18+", salary: "€1,800 – €2,300/month | €11.0–€13.5/hr", note: "5–6 days/week depending on store." },
      { title: "Delivery Driver (parcel / goods)", gender: "Male only", age: "18+", salary: "€2,000 – €2,700/month | €12.0–€16.0/hr", note: "5 days/week or shift-based." },
      { title: "Caregiver / Home-care Worker", gender: "Male & Female", age: "18+", salary: "€1,800 – €2,300/month | €12.5–€16.0/hr", note: "5–6 days/week, shifts possible." },
    ],
    salaryTable: [
      { hours: "Packaging / Warehouse Worker", monthly: "€1,800 – €2,400", annual: "€11.5 – €14.5/hr" },
      { hours: "Store Keeper / Retail Worker", monthly: "€1,800 – €2,300", annual: "€11.0 – €13.5/hr" },
      { hours: "Delivery Driver", monthly: "€2,000 – €2,700", annual: "€12.0 – €16.0/hr" },
      { hours: "Caregiver / Home-care Worker", monthly: "€1,800 – €2,300", annual: "€12.5 – €16.0/hr" },
    ],
    requirements: [
      "Valid passport (personal data page scan)",
      "CV in European format",
      "Work experience certificate (role-dependent, minimum 1 year preferred)",
      "Educational qualifications (role-dependent)",
      "Police Clearance Certificate",
      "Medical fitness certificate (mandatory prior to visa and deployment)",
    ],
    permitTypes: [
      { type: "Standard Work Permit", for: "Contract-based employment with Finnish employer" },
      { type: "Skilled Worker Permit", for: "Specialists, drivers, caregivers" },
      { type: "Seasonal Work Permit", for: "Agriculture, packing, tourism" },
      { type: "EU Blue Card", for: "Highly qualified professionals" },
    ],
    workProcess: [
      "Document Verification: Screening and validating applicant documents — 20–25 working days",
      "Employer Submission: Job offer & contract submission to Finnish authorities — 20–25 working days",
      "Work Permit Processing: Review by Finnish Immigration Service (Migri) — 60–90 working days",
      "Residence Permit Decision: Biometrics & approval notification — 10–15 working days",
      "Pre-Departure Training: Orientation & safety briefing — 7–10 working days",
      "Travel & Deployment: Travel arrangement and final deployment — 8–12 working days",
    ],
    accommodation: "Free shared accommodation provided. 2–4 persons per room. Shared kitchen and bathroom. No family, partners, or pets.",
    eligibleNationalities: ["All nationalities — contact us for eligibility confirmation"],
    important: "Employment Contract: Minimum 2 years (renewable). Probation Period: 6 months (standard in Finland). Overtime paid at legally approved overtime rates. Finnish labor contracts follow collective agreement (CBA) salary rules.",
  },

  /* ─────────────────────────────────────────
     4. GERMANY
  ───────────────────────────────────────── */
  {
    id: "germany",
    country: "Germany",
    flag: "🇩🇪",
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "4–7 months (may vary based on visa and verification procedures)",
    salary: "€2,430 – €4,510/month depending on role",
    workHours: "39–40 hours per week",
    benefits: [
      "Social security registration (health, pension, unemployment, care insurance)",
      "Minimum 20 paid annual leave days",
      "Public holiday benefits according to federal state regulations",
      "Sick leave salary protection up to 6 weeks per illness",
      "Workplace safety protection under German occupational safety rules",
      "PPE and training support where required",
      "Accommodation or commuting assistance (if applicable)",
    ],
    whyChoose: [
      "Germany is Europe's largest economy with world-class wage standards and worker protections.",
      "Monthly salaries from €2,430 to €4,510 — among the highest in Europe.",
      "Mandatory social security covering health, pension, unemployment, and care insurance.",
      "Sick leave salary protection up to 6 weeks per illness.",
      "Full social security registration from day one of employment.",
    ],
    inDemandJobs: [
      { title: "Welder", gender: "Male only", age: "18+", salary: "€3,120 – €4,160/month | €18.00–€24.00/hr", note: "Metal welding, blueprint reading, quality control." },
      { title: "Construction Worker", gender: "Male only", age: "18+", salary: "€2,770 – €3,460/month | €16.00–€20.00/hr", note: "Site labor support, material handling." },
      { title: "Automation Industry Worker", gender: "Male & Female", age: "18+", salary: "€3,290 – €4,510/month | €19.00–€26.00/hr", note: "Machine operation, robotics monitoring." },
      { title: "Fruit Packing Warehouse Worker", gender: "Male & Female", age: "18+", salary: "€2,430 – €2,860/month | €14.00–€16.50/hr", note: "Sorting, packing, warehouse quality work." },
    ],
    salaryTable: [
      { hours: "Welder", monthly: "€3,120 – €4,160", annual: "€18.00 – €24.00/hr" },
      { hours: "Construction Worker", monthly: "€2,770 – €3,460", annual: "€16.00 – €20.00/hr" },
      { hours: "Automation Industry Worker", monthly: "€3,290 – €4,510", annual: "€19.00 – €26.00/hr" },
      { hours: "Fruit Packing Warehouse Worker", monthly: "€2,430 – €2,860", annual: "€14.00 – €16.50/hr" },
    ],
    requirements: [
      "Valid passport",
      "CV in European format",
      "Work experience certificate (role-dependent)",
      "Educational qualifications / professional certifications",
      "Police Clearance Certificate",
      "Medical fitness certificate",
    ],
    permitTypes: [
      { type: "Skilled Worker Visa", for: "Qualified professionals with German-recognised qualifications" },
      { type: "EU Blue Card", for: "Highly qualified workers earning above threshold salary" },
      { type: "Seasonal Work Permit", for: "Agriculture, hospitality, food processing" },
      { type: "General Employment Visa", for: "Roles approved by Federal Employment Agency" },
    ],
    workProcess: [
      "Candidate Assessment: Skill screening and interview — 10–15 working days",
      "Employment Approval: Federal Employment Agency approval (if required) — 4–8 weeks",
      "Visa Processing: Embassy/Consulate processing — 4–12 weeks",
      "Qualification Recognition: If applicable — 2–6 weeks",
      "Pre-departure Preparation: Travel arrangement — 2–3 weeks",
    ],
    accommodation: "Accommodation or commuting assistance provided where applicable. Shared or individual based on employer agreement.",
    eligibleNationalities: ["All nationalities — contact us for eligibility confirmation"],
    important: "Wages follow German minimum wage standards. Social security contributions are mandatory. Total Estimated Processing Time: 4–7 months. This Recruitment Demand Letter confirms manpower demand for deployment to Germany.",
  },

  /* ─────────────────────────────────────────
     5. GREECE
  ───────────────────────────────────────── */
  {
    id: "greece",
    country: "Greece",
    flag: "🇬🇷",
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "115–135 Working Days",
    salary: "€950 – €1,200/month depending on job category and experience",
    workHours: "40–48 hours/week per Greek labor law (8 hrs/day, 5–6 days/week)",
    benefits: [
      "Free company-provided housing / accommodation",
      "Worksite transport included",
      "Health Insurance provided as per Greek labor regulations",
      "Food Allowance included based on job category",
      "PPE (Safety Gear) provided where applicable",
      "Annual Leave as per Greece labor law",
      "Emergency Medical Support provided to all workers",
    ],
    whyChoose: [
      "Greece offers thousands of vacancies across agriculture, food processing, animal care, and machinery operation.",
      "Competitive salaries of €950–€1,200/month with accommodation and transport provided.",
      "Full employer-sponsored benefits including health insurance, food allowance, and PPE.",
      "EU member state with strong legal worker protections.",
      "Minimum 330 total vacancies across all job categories currently available.",
    ],
    inDemandJobs: [
      { title: "Agriculture Worker", gender: "Male & Female", age: "18+", salary: "€950 – €1,050/month", note: "48 vacancies. Field & Farm Category. 8 hrs/day, 6 days/week." },
      { title: "Greenhouse Helper", gender: "Male & Female", age: "18+", salary: "€950 – €1,050/month", note: "26 vacancies. 8 hrs/day, 6 days/week." },
      { title: "Field Crop Worker", gender: "Male & Female", age: "18+", salary: "€1,000 – €1,150/month", note: "22 vacancies. 8 hrs/day, 6 days/week." },
      { title: "Animal Farm Helper", gender: "Male & Female", age: "18+", salary: "€1,000 – €1,150/month", note: "28 vacancies. Animal Care. 8 hrs/day, 6 days/week." },
      { title: "Livestock Care Worker", gender: "Male & Female", age: "18+", salary: "€1,050 – €1,200/month", note: "20 vacancies. 8 hrs/day, 6 days/week." },
      { title: "Forklift Operator", gender: "Male only", age: "18+", salary: "€1,100 – €1,200/month", note: "16 vacancies. Machinery & Equipment. 8 hrs/day, 5–6 days/week." },
      { title: "Tractor Driver", gender: "Male only", age: "18+", salary: "€1,100 – €1,200/month", note: "18 vacancies. 8 hrs/day, 6 days/week." },
      { title: "Machine Operator", gender: "Male & Female", age: "18+", salary: "€1,050 – €1,200/month", note: "22 vacancies. 8 hrs/day, 5–6 days/week." },
      { title: "Site Supervisor", gender: "Male only", age: "25+", salary: "€1,150 – €1,200/month", note: "12 vacancies. Supervisory & Skilled. 8 hrs/day, 6 days/week." },
      { title: "Farm Team Leader", gender: "Male & Female", age: "22+", salary: "€1,100 – €1,200/month", note: "14 vacancies. 8 hrs/day, 6 days/week." },
      { title: "Food Processing Worker", gender: "Male & Female", age: "18+", salary: "€950 – €1,050/month", note: "30 vacancies. Agriculture Processing. 8 hrs/day, 5–6 days/week." },
      { title: "Packaging Assistant", gender: "Male & Female", age: "18+", salary: "€950 – €1,050/month", note: "34 vacancies. 8 hrs/day, 5–6 days/week." },
      { title: "Factory Helper", gender: "Male & Female", age: "18+", salary: "€950 – €1,050/month", note: "40 vacancies. 8 hrs/day, 5–6 days/week." },
    ],
    requirements: [
      "Passport Copy (clear PDF copy of valid passport)",
      "Passport Size Photo (recent, white background)",
      "CV / Resume (updated and complete)",
      "Experience Certificate (required for skilled/supervisory categories)",
      "Educational Certificates (as per job category)",
      "Driving License (for machinery or driving-related roles)",
    ],
    permitTypes: [
      { type: "Standard Work Permit", for: "Contract-based employment with Greek employer" },
      { type: "Seasonal Work Permit", for: "Agriculture, tourism, food processing" },
      { type: "Skilled Worker Permit", for: "Supervisory and machinery roles" },
      { type: "EU Blue Card", for: "Highly qualified professionals" },
    ],
    workProcess: [
      "Offer Letter: Issuance of official employment offer — 15–25 working days",
      "Work Permit Process: Submission & approval of work permit — 65–80 working days",
      "Visa Processing: Embassy submission & final visa issuance — within 100 working days",
    ],
    accommodation: "Free company-provided housing. Shared rooms. Transport to worksite included. No family, partners, or pets.",
    eligibleNationalities: ["All nationalities — contact us for eligibility confirmation"],
    important: "Contract Duration: Minimum 2 years (renewable). Working Hours: 40–48 hours/week per Greek labor law. Overtime: Paid according to labor regulations. Probation Period: 3 months. Medical Fitness: Mandatory. Total Estimated Processing Time: 115–135 Working Days.",
  },

  /* ─────────────────────────────────────────
     6. MALTA
  ───────────────────────────────────────── */
  {
    id: "malta",
    country: "Malta",
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "70–120 working days (approx. 3–5 months)",
    salary: "€1,200 – €1,900/month depending on role",
    workHours: "Standard 40 hours per week (8 hrs/day)",
    benefits: [
      "Accommodation support or shared housing (if offered by employer)",
      "Transportation allowance or workplace transport arrangement",
      "Work uniform, PPE, and safety equipment",
      "Medical coverage under Malta's public healthcare system",
      "Paid annual leave (approximately 24 days per year)",
      "Statutory bi-annual bonus payments where applicable",
      "Safe working environment complying with occupational safety regulations",
    ],
    whyChoose: [
      "Malta is a full EU member — work experience and residency here carries full EU weight.",
      "English is widely spoken, making it much easier for international workers to settle in.",
      "Booming tourism sector with year-round demand in hospitality, construction, and services.",
      "Mediterranean lifestyle with excellent quality of life and affordable living costs.",
      "Hourly overtime typically paid at 150% of the standard hourly rate.",
    ],
    inDemandJobs: [
      { title: "Construction Site Labourer", gender: "Male only", age: "18+", salary: "€1,300 – €1,700/month | €7.5–€9.8/hr", note: "5–6 days/week. ~8 hrs/day." },
      { title: "Maintenance Technician / Handyman", gender: "Male only", age: "18+", salary: "€1,400 – €1,900/month | €8.1–€11.0/hr", note: "5 days/week. ~8 hrs/day." },
      { title: "Warehouse / Packaging Worker", gender: "Male & Female", age: "18+", salary: "€1,250 – €1,600/month | €7.2–€9.2/hr", note: "Shift based. ~8 hrs/day." },
      { title: "Delivery Driver / Assistant", gender: "Male only", age: "18+", salary: "€1,300 – €1,700/month | €7.5–€9.8/hr", note: "5–6 days/week. ~8 hrs/day." },
      { title: "Hotel Cleaner / Housekeeping Staff", gender: "Male & Female", age: "18+", salary: "€1,200 – €1,500/month | €6.9–€8.7/hr", note: "Shift based. ~8 hrs/day." },
    ],
    salaryTable: [
      { hours: "Construction Site Labourer", monthly: "€1,300 – €1,700", annual: "€7.5 – €9.8/hr" },
      { hours: "Maintenance Technician", monthly: "€1,400 – €1,900", annual: "€8.1 – €11.0/hr" },
      { hours: "Warehouse / Packaging Worker", monthly: "€1,250 – €1,600", annual: "€7.2 – €9.2/hr" },
      { hours: "Delivery Driver / Assistant", monthly: "€1,300 – €1,700", annual: "€7.5 – €9.8/hr" },
      { hours: "Hotel Cleaner / Housekeeping", monthly: "€1,200 – €1,500", annual: "€6.9 – €8.7/hr" },
    ],
    requirements: [
      "Valid passport (minimum 1 year validity)",
      "Passport size photo",
      "CV in European format",
      "Work experience certificate (role-dependent)",
      "Educational qualifications",
      "Medical fitness clearance (may be required)",
    ],
    permitTypes: [
      { type: "Single Permit (Malta)", for: "Combined work and residence permit via Jobsplus / Identity Malta" },
      { type: "Skilled Worker Permit", for: "Certified professionals — technicians, drivers" },
      { type: "Seasonal Work Permit", for: "Tourism and hospitality roles" },
    ],
    workProcess: [
      "Document Verification & Job Matching: Candidate screening and assessment — 10–15 working days",
      "Employer Application Submission: Submission to Jobsplus / Identity Malta — 15–25 working days",
      "Work Permit Processing: Review and approval — 30–60 days",
      "Visa Application (if required): Embassy or consulate processing — 10–20 days",
      "Pre-Departure Preparation: Orientation and travel arrangement — 5–10 days",
    ],
    accommodation: "Accommodation support or shared housing provided where applicable. Employer-dependent.",
    eligibleNationalities: ["All nationalities — contact us for eligibility confirmation"],
    important: "Contract Type: Fixed-term (1–3 years) for foreign workers. Hourly rate calculated based on approximately 173 working hours per month. Overtime paid at 150% of standard hourly rate. Salaries may include allowances and statutory bonuses.",
  },

  /* ─────────────────────────────────────────
     7. MOLDOVA
  ───────────────────────────────────────── */
  {
    id: "moldova",
    country: "Moldova",
    
    region: "Europe",
    visaType: "E-Visa",
    category: "Work Permit",
    processingTime: "62–97 working days (approximately 3–4 months)",
    salary: "€600 – €1,400/month depending on role",
    workHours: "8 hours/day, 5–6 days/week (40–48 hrs/week)",
    benefits: [
      "Accommodation: Shared accommodation provided or arranged by the employer",
      "Transportation: Workplace transportation provided or subsidized by the employer",
      "Work Uniform & Safety Equipment: Necessary uniforms, tools, and PPE provided",
      "Health Insurance: Mandatory health insurance coverage in accordance with Moldovan regulations",
      "Paid Leave: Paid annual leave and public holidays as per Moldovan labor law",
      "Safe Working Environment: Employers comply with occupational health and safety standards",
    ],
    whyChoose: [
      "Moldova has 50,000+ job openings in agriculture, food processing, transport, construction, and textiles.",
      "Very low cost of living — save significantly more of your earnings.",
      "Employer-sponsored residency permit valid for 1–2 years with renewal options.",
      "Your first European work experience — a strong stepping stone to other EU countries.",
      "Full support from day one: accommodation, meals, and transport all provided by employer.",
    ],
    inDemandJobs: [
      { title: "Warehouse Worker", gender: "Male & Female", age: "18+", salary: "€650 – €850/month", note: "8 hrs/day, 5–6 days/week." },
      { title: "Warehouse Packing Worker", gender: "Male & Female", age: "18+", salary: "€650 – €850/month", note: "8 hrs/day, 5–6 days/week." },
      { title: "Factory Worker", gender: "Male & Female", age: "18+", salary: "€700 – €900/month", note: "8 hrs/day, 5–6 days/week." },
      { title: "Construction Worker", gender: "Male only", age: "18–48", salary: "€800 – €1,100/month", note: "8 hrs/day, 5–6 days/week." },
      { title: "Cleaner", gender: "Male & Female", age: "18+", salary: "€600 – €800/month", note: "8 hrs/day, 5–6 days/week." },
      { title: "Fruit Packing Worker", gender: "Male & Female", age: "18+", salary: "€650 – €900/month", note: "8 hrs/day, Seasonal / 5–6 days." },
      { title: "Butcher", gender: "Male only", age: "18+", salary: "€900 – €1,200/month", note: "8 hrs/day, 5–6 days/week." },
      { title: "Electrician", gender: "Male only", age: "18+", salary: "€1,000 – €1,400/month", note: "8 hrs/day, 5 days/week." },
      { title: "Plumber", gender: "Male only", age: "18+", salary: "€950 – €1,300/month", note: "8 hrs/day, 5 days/week." },
      { title: "Forklift Operator", gender: "Male only", age: "18+", salary: "€750 – €1,000/month", note: "8 hrs/day, 5–6 days/week." },
    ],
    salaryTable: [
      { hours: "Warehouse Worker", monthly: "€650 – €850", annual: "8 hrs/day" },
      { hours: "Factory Worker", monthly: "€700 – €900", annual: "8 hrs/day" },
      { hours: "Construction Worker", monthly: "€800 – €1,100", annual: "8 hrs/day" },
      { hours: "Butcher", monthly: "€900 – €1,200", annual: "8 hrs/day" },
      { hours: "Electrician", monthly: "€1,000 – €1,400", annual: "8 hrs/day" },
      { hours: "Plumber", monthly: "€950 – €1,300", annual: "8 hrs/day" },
    ],
    requirements: [
      "Valid international passport (minimum 12 months validity from application date)",
      "CV in European format with education, work history, and skills",
      "Work experience proof in a relevant or similar field (minimum 1 year)",
      "Coloured scan of passport personal data page",
      "Minimum educational certificate (primary or secondary level, as per job type)",
      "Short video (1–2 minutes) in English: introduce yourself, state nationality and work experience",
      "Second short video clip showing you performing relevant work tasks",
    ],
    permitTypes: [
      { type: "Standard Work Permit", for: "Contract-based employment with Moldovan company" },
      { type: "Seasonal Work Permit", for: "Agriculture or tourism (up to 6 months)" },
      { type: "Skilled Work Permit", for: "Logistics, IT, or healthcare specialists" },
      { type: "Temporary Residence Permit", for: "Combined work and living permit for 1–2 years" },
    ],
    workProcess: [
      "Candidate Screening & Selection: Document verification and job matching — 7–10 working days",
      "Employer Approval & Contract Issuance: Employment offer and contract signing — 10–15 working days",
      "Work Permit Processing: Submission to Moldovan authorities — 30–45 calendar days",
      "Visa Application: National employment visa processing — 10–20 working days",
      "Pre-Departure & Deployment: Orientation and travel arrangements — 5–7 working days",
    ],
    accommodation: "Provided by employer. Shared accommodation. Utility or partial deductions may apply.",
    eligibleNationalities: ["Bangladesh", "India", "Nepal", "Sri Lanka", "Philippines", "African countries"],
    important: "Employment Contract: Fixed-term 1–2 years, renewable. Probation Period: Typically 1–3 months. The Type D visa is issued specifically for the approved employer and position.",
  },

  /* ─────────────────────────────────────────
     8. NORTH MACEDONIA
  ───────────────────────────────────────── */
  {
    id: "north-macedonia",
    country: "North Macedonia",
    
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "Approximately 73–140 working days (3–6 months)",
    salary: "€950 – €1,350/month depending on role",
    workHours: "40 hours per week (8 hrs/day, 5–6 days/week)",
    benefits: [
      "Subsidized shared accommodation or housing allowance",
      "Transportation to and from the workplace or monthly transport allowance",
      "Mandatory health insurance registration under the Macedonian state system",
      "Full work accident and occupational insurance coverage",
      "Daily meal allowance or subsidized meals at workplace canteen",
      "Initial airfare reimbursement (subject to terms, often after probation)",
      "Full personal protective equipment (PPE) and uniforms provided",
      "Paid annual leave of minimum 20 working days per year",
      "Paid sick leave in accordance with Macedonian social security regulations",
      "Safe and regulated working environment compliant with national and EU standards",
    ],
    whyChoose: [
      "North Macedonia is an EU candidate country — work experience here can strengthen your future EU applications.",
      "Low cost of living with opportunities in construction, hospitality, manufacturing and logistics.",
      "Welcoming environment for foreign workers with strong employer support.",
      "Overtime compensated at 135% of regular wage as per Macedonian Labor Law.",
      "SNJ GlobalRoutes provides complete end-to-end support including documentation and deployment.",
    ],
    inDemandJobs: [
      { title: "Factory Worker (Production)", gender: "Male & Female", age: "18+", salary: "€1,000 – €1,250/month | €5.80–€7.20/hr", note: "5–6 days/week, shift work, machine operation." },
      { title: "Packing & Sorting Operator", gender: "Male & Female", age: "18+", salary: "€950 – €1,150/month | €5.50–€6.60/hr", note: "5–6 days/week, production line, quality control." },
      { title: "Storekeeper / Inventory Controller", gender: "Male & Female", age: "18+", salary: "€1,100 – €1,350/month | €6.40–€7.80/hr", note: "5 days/week, stock management and documentation." },
      { title: "Fruit Packing & Grading Specialist", gender: "Male & Female", age: "18+", salary: "€980 – €1,200/month | €5.70–€6.90/hr", note: "5–6 days/week, seasonal demand, fresh produce." },
      { title: "Warehouse Operator / Forklift Driver", gender: "Male only", age: "18+", salary: "€1,050 – €1,300/month | €6.10–€7.50/hr", note: "5–6 days/week, loading/unloading, logistics." },
    ],
    salaryTable: [
      { hours: "Factory Worker (Production)", monthly: "€1,000 – €1,250", annual: "€5.80 – €7.20/hr" },
      { hours: "Packing & Sorting Operator", monthly: "€950 – €1,150", annual: "€5.50 – €6.60/hr" },
      { hours: "Storekeeper / Inventory Controller", monthly: "€1,100 – €1,350", annual: "€6.40 – €7.80/hr" },
      { hours: "Fruit Packing & Grading Specialist", monthly: "€980 – €1,200", annual: "€5.70 – €6.90/hr" },
      { hours: "Warehouse Operator / Forklift Driver", monthly: "€1,050 – €1,300", annual: "€6.10 – €7.50/hr" },
    ],
    requirements: [
      "Valid passport (minimum 1 year validity)",
      "CV in European format",
      "Work experience certificate (role-dependent)",
      "Educational qualifications",
      "Police Clearance Certificate",
      "Medical fitness certificate (mandatory prior to visa issuance and upon arrival)",
    ],
    permitTypes: [
      { type: "Standard Work Permit", for: "Contract-based employment with Macedonian employer (min 1 year)" },
      { type: "Seasonal Work Permit", for: "Agriculture, packing, food processing" },
      { type: "Skilled Worker Permit", for: "Storekeeper, forklift operator, supervisory roles" },
    ],
    workProcess: [
      "Document Verification: Screening and validation of candidate documents — 10–15 working days",
      "Labor Market Test: Approval from Employment Service Agency of North Macedonia — 15–30 working days",
      "Work Permit Processing: Submission and approval by Ministry of Interior — 30–60 working days",
      "Visa Application: Submission at Macedonian diplomatic mission — 10–20 working days",
      "Pre-Departure Training: Orientation, safety briefing, cultural guidance — 3–5 working days",
      "Travel & Deployment: Flight arrangements and onboarding — 5–10 working days",
    ],
    accommodation: "Subsidized shared accommodation or housing allowance. No family, partners, or pets.",
    eligibleNationalities: ["All nationalities — contact us for details"],
    important: "Employment Contract Duration: Minimum 1 year, renewable by mutual consent. Overtime Compensation: As per Macedonian Labor Law (typically 135% of regular wage). Probation Period: Up to 6 months. Processing Fee: €2,500 total (€500 on process start, €500 after offer letter, €500 after work permit, €1,000 after visa grant).",
  },

  /* ─────────────────────────────────────────
     9. NEW ZEALAND
  ───────────────────────────────────────── */
  {
    id: "new-zealand",
    country: "New Zealand",
    
    region: "Pacific",
    visaType: "E-Visa",
    category: "Work Permit",
    processingTime: "120 Working Days",
    salary: "NZD 4,600 – 12,700/month depending on role",
    workHours: "8 hours/day, 5 days/week (40 hrs/week)",
    benefits: [
      "Accommodation: Fully furnished shared/single housing",
      "Health Insurance: Comprehensive medical coverage for employees",
      "Transportation: Provided to workplace if required",
      "Air Ticket: Provided for candidates from their home country to New Zealand",
      "Training & Orientation: Pre-departure and on-job training",
      "Personal Protective Equipment (PPE): Provided where applicable",
      "Paid Leave: As per New Zealand labor laws",
      "Public Holidays: Observed according to New Zealand regulations",
    ],
    whyChoose: [
      "New Zealand consistently ranks among the world's best countries for quality of life and worker rights.",
      "Strong demand in healthcare, IT, construction, and caregiving sectors.",
      "Air ticket provided from home country to New Zealand.",
      "Comprehensive health insurance and accommodation fully provided.",
      "Contracts valid for 2 years, renewable — strong long-term opportunity.",
    ],
    inDemandJobs: [
      { title: "Doctor", gender: "Male & Female", age: "25+", salary: "NZD 12,700/month | ≈ NZD 79.4/hr", note: "8 vacancies. Hospital & Clinic. Min 3 years experience. Professional licence required." },
      { title: "Nurse", gender: "Male & Female", age: "22+", salary: "NZD 8,400 – 10,000/month | ≈ NZD 52.5–62.5/hr", note: "18 vacancies. Hospital / Clinic / Aged Care. Min 2 years experience. Nursing licence required." },
      { title: "Pharmacist", gender: "Male & Female", age: "22+", salary: "NZD 8,000 – 11,000/month | ≈ NZD 50–68.7/hr", note: "6 vacancies. Pharmacy & Hospital. Professional licence required." },
      { title: "Caregiver / Health-Care Assistant", gender: "Male & Female", age: "18+", salary: "NZD 4,600 – 5,200/month | ≈ NZD 28.7–32.5/hr", note: "12 vacancies. Home & Elderly Care. Min 1 year experience." },
      { title: "IT Specialist", gender: "Male & Female", age: "22+", salary: "NZD 6,500 – 9,200/month | ≈ NZD 40.6–57.5/hr", note: "9 vacancies. Office / Remote. IT certification required. Min 2 years experience." },
    ],
    salaryTable: [
      { hours: "Doctor", monthly: "NZD 12,700", annual: "≈ NZD 79.4/hr" },
      { hours: "Nurse", monthly: "NZD 8,400 – 10,000", annual: "≈ NZD 52.5–62.5/hr" },
      { hours: "Pharmacist", monthly: "NZD 8,000 – 11,000", annual: "≈ NZD 50–68.7/hr" },
      { hours: "Caregiver / Health-Care Assistant", monthly: "NZD 4,600 – 5,200", annual: "≈ NZD 28.7–32.5/hr" },
      { hours: "IT Specialist", monthly: "NZD 6,500 – 9,200", annual: "≈ NZD 40.6–57.5/hr" },
    ],
    requirements: [
      "Passport Scan (valid minimum 6 months)",
      "CV / Resume (professional format)",
      "Passport-size Photographs (2–4 recent copies)",
      "Educational Certificates (degree, diploma, or relevant certifications)",
      "Work Experience Certificates (from previous employers)",
      "Police Clearance (local and international if applicable)",
      "Medical Certificate (from licensed medical practitioner)",
      "Professional License (if applicable for doctor, nurse, pharmacist)",
      "English Language Test (IELTS / TOEFL if required)",
      "Reference Letters (optional)",
    ],
    permitTypes: [
      { type: "Accredited Employer Work Visa (AEWV)", for: "Most common route — requires accredited NZ employer" },
      { type: "Skilled Migrant Category", for: "Points-based permanent residence pathway" },
      { type: "Seasonal Work Visa", for: "Agriculture and horticulture roles" },
      { type: "Essential Skills Work Visa", for: "Specific shortage occupations" },
    ],
    workProcess: [
      "Document Verification: Screening and validation — 15 working days",
      "Visa Application Submission: Preparation and submission — 30 working days",
      "Approval & Work Permit: Government processing — 45 working days",
      "Pre-Departure Training: Orientation and safety briefing — 15 working days",
      "Travel & Deployment: Travel arrangement and deployment — 15 working days",
    ],
    accommodation: "Fully furnished shared/single housing provided by employer.",
    eligibleNationalities: ["All nationalities — contact us for eligibility"],
    important: "Compliance with New Zealand Health & Safety Act is mandatory. Contracts valid for 2 years, renewable. Total processing time from document submission to placement: 120 working days.",
  },

  /* ─────────────────────────────────────────
     10. NORWAY
  ───────────────────────────────────────── */
  {
    id: "norway",
    country: "Norway",
    
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "120 Working Days",
    salary: "€2,125 – €2,592/month depending on role (1 NOK ≈ 0.085 EUR)",
    workHours: "8 hrs/day, 5–6 days/week depending on job",
    benefits: [
      "Fully furnished accommodation for all employees",
      "Daily food allowance",
      "Health insurance coverage",
      "Transportation to and from the workplace",
      "Personal Protective Equipment (PPE) for applicable roles",
      "Support for legal and visa-related formalities",
    ],
    whyChoose: [
      "Norway offers some of the highest wages in Europe — €2,125–€2,592/month even for non-skilled roles.",
      "All accommodation, food, health insurance, and transport provided by employer.",
      "Strong worker protections under Norwegian labor law.",
      "Probation period typically only 3 months.",
      "SNJ GlobalRoutes provides complete end-to-end support for your work permit and visa application.",
    ],
    inDemandJobs: [
      { title: "Fruit Packing Worker", gender: "Male & Female", age: "18+", salary: "€2,125/month", note: "20 vacancies. Packaging & Sorting. Non-Skilled. Packing, sorting, labeling, maintaining cleanliness." },
      { title: "Warehouse Worker", gender: "Male & Female", age: "18+", salary: "€2,295/month", note: "15 vacancies. Stock & Loading Work. Non-Skilled/Semi-Skilled. Loading/unloading, scanning, stock keeping." },
      { title: "Factory Worker", gender: "Male & Female", age: "18+", salary: "€2,253/month", note: "20 vacancies. General Industrial Labour. Non-Skilled. Machine assistance, assembly line, packing." },
      { title: "Plumber", gender: "Male only", age: "18+", salary: "€2,592/month", note: "8 vacancies. Skilled. Pipe installation, repair, water system maintenance." },
      { title: "Carpenter", gender: "Male only", age: "18+", salary: "€2,508/month", note: "10 vacancies. Skilled. Wood cutting, installation, finishing, repairs." },
    ],
    salaryTable: [
      { hours: "Fruit Packing Worker", monthly: "€2,125", annual: "Non-Skilled" },
      { hours: "Warehouse Worker", monthly: "€2,295", annual: "Non-Skilled / Semi-Skilled" },
      { hours: "Factory Worker", monthly: "€2,253", annual: "Non-Skilled" },
      { hours: "Plumber", monthly: "€2,592", annual: "Skilled" },
      { hours: "Carpenter", monthly: "€2,508", annual: "Skilled" },
    ],
    requirements: [
      "Valid passport",
      "CV in European format",
      "Work experience certificate (role-dependent)",
      "Educational qualifications",
      "Police Clearance Certificate",
      "Medical fitness certificate",
    ],
    permitTypes: [
      { type: "Skilled Worker Permit", for: "Plumbers, carpenters, qualified tradespeople" },
      { type: "Standard Work Permit", for: "Warehouse, factory, packing workers" },
      { type: "Seasonal Work Permit", for: "Fruit packing and agricultural roles" },
    ],
    workProcess: [
      "Document Verification: Screening and validation — 15 working days",
      "Visa Application: Preparation and submission — 25 working days",
      "Approval & Work Permit: Government processing — 40 working days",
      "Pre-departure Training: Orientation and safety preparation — 20 working days",
      "Travel & Deployment: Final travel arrangements & deployment — 20 working days",
    ],
    accommodation: "Fully furnished accommodation for all employees. Provided by employer.",
    eligibleNationalities: ["All nationalities — contact us for eligibility confirmation"],
    important: "Employment is in accordance with Norwegian labor laws and regulations. Probation period as per employment contract (usually 3 months). Contract renewal and termination policies as per Norwegian labor law.",
  },

  /* ─────────────────────────────────────────
     11. POLAND
  ───────────────────────────────────────── */
  {
    id: "poland",
    country: "Poland",
    
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "4–5 months (may vary depending on government and visa appointment schedules)",
    salary: "€980 – €1,350/month depending on role (1 EUR ≈ 4.55 PLN)",
    workHours: "40 hours per week as per Polish labor law (~8 hrs/day)",
    benefits: [
      "Free shared accommodation (provided by employer)",
      "Transportation between residence and workplace",
      "Medical insurance coverage under Polish social security system (ZUS)",
      "Food allowance or employer-provided meals (role dependent)",
      "Personal Protective Equipment (PPE) for industrial jobs",
      "Minimum 20 paid annual leave days per year",
      "Paid sick leave benefits",
      "Safe working environment complying with occupational safety standards",
    ],
    whyChoose: [
      "Poland has 150,000+ job openings across IT, healthcare, construction, manufacturing, and logistics.",
      "Employment follows Polish Collective Bargaining Agreement (CBA) standards guaranteeing fair wages.",
      "Free accommodation, transport, and meals provided by employer.",
      "Minimum wage protection guaranteed under Polish law.",
      "Medical insurance via ZUS (Polish social security system) from day one.",
    ],
    inDemandJobs: [
      { title: "Factory Worker", gender: "Male & Female", age: "18+", salary: "€1,050 – €1,350/month | €5.50–€7.00/hr", note: "5–6 days/week. ~8 hrs/day." },
      { title: "Warehouse Worker", gender: "Male & Female", age: "18+", salary: "€1,000 – €1,300/month | €5.20–€6.80/hr", note: "5–6 days/week. ~8 hrs/day." },
      { title: "Fruit Packing Worker", gender: "Male & Female", age: "18+", salary: "€980 – €1,260/month | €5.00–€6.50/hr", note: "Seasonal/Shift-based. ~8 hrs/day." },
      { title: "Vegetable Packing Worker", gender: "Male & Female", age: "18+", salary: "€980 – €1,260/month | €5.00–€6.50/hr", note: "Seasonal/Shift-based. ~8 hrs/day." },
    ],
    salaryTable: [
      { hours: "Factory Worker", monthly: "€1,050 – €1,350", annual: "€5.50 – €7.00/hr" },
      { hours: "Warehouse Worker", monthly: "€1,000 – €1,300", annual: "€5.20 – €6.80/hr" },
      { hours: "Fruit Packing Worker", monthly: "€980 – €1,260", annual: "€5.00 – €6.50/hr" },
      { hours: "Vegetable Packing Worker", monthly: "€980 – €1,260", annual: "€5.00 – €6.50/hr" },
    ],
    requirements: [
      "Valid passport (first page scan)",
      "CV in European format",
      "Work experience proof in related field",
      "Educational qualification certificate",
      "Police Clearance Certificate with Apostille (for drivers)",
      "Medical Fitness Certificate (mandatory prior to visa issuance)",
      "All documents translated into Polish or English",
    ],
    permitTypes: [
      { type: "Type A – Contract Work", for: "Standard contract-based work with Polish employer" },
      { type: "Type B – Senior / Specialist", for: "Manager or senior position (6+ months)" },
      { type: "Type C – Polish Branch", for: "Work at Polish branch of a foreign company" },
      { type: "Type S – Seasonal Work", for: "Agriculture, gardening, tourism" },
    ],
    workProcess: [
      "Document screening and CV review — 2–3 weeks",
      "Employer matching and job offer issuance — 2–4 weeks",
      "Work permit application submitted at Voivodeship Office — processing takes 2–3 months",
      "Visa application begins only after work permit approval — 3–4 weeks",
      "Pre-departure orientation and travel — 1–2 weeks",
    ],
    accommodation: "Free shared rooms (2–4 persons). Furnished. Shared kitchen and bathroom. No family, partners, or pets.",
    eligibleNationalities: ["All nationalities except Somalia, Iraq, Iran, Cuba, Libya, Syria (ages 18–45)"],
    important: "Employment follows Polish Collective Bargaining Agreement (CBA) standards. Minimum wage protection guaranteed. Overtime compensation paid according to Polish labor law. Contract Duration: Minimum 1 year (renewable). Probation Period: 3 months.",
  },

  /* ─────────────────────────────────────────
     12. ROMANIA
  ───────────────────────────────────────── */
  {
    id: "romania",
    country: "Romania",
    
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "85–157 working days (approximately 3–5 months)",
    salary: "€650 – €1,500/month depending on role",
    workHours: "40 hours/week as per Romanian Labor Code (~8 hrs/day)",
    benefits: [
      "Free shared accommodation (may vary by employer and location)",
      "Transportation to and from the workplace (some employers provide, others may offer allowance)",
      "Health insurance (provided per Romanian employment law)",
      "Food allowance / meals (provided for some roles; may depend on shift or company policy)",
      "Personal protective equipment (PPE) for industrial and construction roles",
      "Paid annual leave — minimum 20 days/year per Romanian Labor Code",
      "Sick leave benefits as per Romanian labor regulations",
      "Safe and compliant working environment following Romanian Work Safety and Health regulations",
    ],
    whyChoose: [
      "Romania offers competitive European wages with low living costs.",
      "Strong demand across construction, warehousing, welding, driving, and skilled trades.",
      "Employer-provided accommodation and transport minimise your expenses.",
      "Full legal protection under Romanian labor law from day one.",
      "SNJ GlobalRoutes provides complete end-to-end support.",
    ],
    inDemandJobs: [
      { title: "Construction Worker", gender: "Male only", age: "18+", salary: "€800 – €1,100/month | €4.5–€6.0/hr", note: "5–6 days/week depending on project." },
      { title: "Warehouse Worker", gender: "Male & Female", age: "18+", salary: "€700 – €950/month | €4.0–€5.5/hr", note: "5 days/week." },
      { title: "Packing Worker", gender: "Male & Female", age: "18+", salary: "€650 – €900/month | €3.8–€5.2/hr", note: "5–6 days/week, shift work possible." },
      { title: "Welder", gender: "Male only", age: "18+", salary: "€1,000 – €1,400/month | €5.5–€8.0/hr", note: "5 days/week, overtime possible." },
      { title: "Plumber", gender: "Male only", age: "18+", salary: "€900 – €1,300/month | €5.0–€7.5/hr", note: "5 days/week." },
      { title: "Delivery Driver", gender: "Male only", age: "18+", salary: "€800 – €1,200/month | €4.5–€6.5/hr", note: "5–6 days/week, shift or route-based." },
      { title: "Electrician", gender: "Male only", age: "18+", salary: "€1,000 – €1,500/month | €5.5–€8.5/hr", note: "5 days/week, project-based." },
    ],
    salaryTable: [
      { hours: "Construction Worker", monthly: "€800 – €1,100", annual: "€4.5 – €6.0/hr" },
      { hours: "Warehouse Worker", monthly: "€700 – €950", annual: "€4.0 – €5.5/hr" },
      { hours: "Packing Worker", monthly: "€650 – €900", annual: "€3.8 – €5.2/hr" },
      { hours: "Welder", monthly: "€1,000 – €1,400", annual: "€5.5 – €8.0/hr" },
      { hours: "Plumber", monthly: "€900 – €1,300", annual: "€5.0 – €7.5/hr" },
      { hours: "Delivery Driver", monthly: "€800 – €1,200", annual: "€4.5 – €6.5/hr" },
      { hours: "Electrician", monthly: "€1,000 – €1,500", annual: "€5.5 – €8.5/hr" },
    ],
    requirements: [
      "Valid passport (personal data page scan)",
      "CV in European format",
      "Work experience certificate (role-dependent)",
      "Educational qualifications",
      "Police Clearance Certificate",
      "Medical Fitness Certificate (mandatory prior to visa and deployment)",
    ],
    permitTypes: [
      { type: "Standard Work Permit", for: "Contract-based employment with Romanian employer" },
      { type: "Skilled Worker Permit", for: "Welders, electricians, plumbers, drivers" },
      { type: "Seasonal Work Permit", for: "Packing, agriculture, tourism roles" },
    ],
    workProcess: [
      "Document Verification: Screening and validating applicant documents — 10–15 working days",
      "Employer Submission: Job offer & contract submission to Romanian Immigration / Work Authority — 10–20 working days",
      "Work Permit Processing: Review by Romanian authorities — 45–90 working days",
      "Residence Permit Decision: Biometrics & approval notification — 10–15 working days",
      "Pre-Departure Training: Orientation, safety & Romania culture briefing — 5–7 working days",
      "Travel & Deployment: Travel arrangement and final deployment — 5–10 working days",
    ],
    accommodation: "Free shared accommodation (may vary by employer and location). 2–4 persons per room. No family, partners, or pets.",
    eligibleNationalities: ["All nationalities — contact us for eligibility confirmation"],
    important: "Employment Contract: Minimum 2 years (renewable). Probation Period: 3–6 months. Overtime paid at legally approved rates. Romanian labor contracts follow local labor laws guaranteeing fair wages and regulated working conditions.",
  },

  /* ─────────────────────────────────────────
     13. SERBIA
  ───────────────────────────────────────── */
  {
    id: "serbia",
    country: "Serbia",
    
    region: "Europe",
    visaType: "E-Visa",
    category: "Work Permit",
    processingTime: "110–124 Working Days",
    salary: "€711 – €996/month depending on role",
    workHours: "40–48 hours per week (8 hrs/day, 5–6 days/week)",
    benefits: [
      "Free Accommodation",
      "Transportation to and from workplace",
      "Health Insurance",
      "Food Allowance (as per job role)",
      "Personal Protective Equipment (PPE) where required",
      "Paid Annual Leave according to Serbia's labor laws",
      "Medical support and emergency coverage",
    ],
    whyChoose: [
      "Serbia offers 150,000+ job opportunities across hospitality, construction, manufacturing, and logistics.",
      "Affordable living costs — Belgrade and Novi Sad are vibrant, modern cities with low expenses.",
      "Strong pathway to permanent residency and eventually Serbian citizenship.",
      "Serbia is strategically located in Central Europe — ideal for business, travel, and regional connections.",
      "Free accommodation, transport, health insurance, and food allowance provided.",
    ],
    inDemandJobs: [
      { title: "Construction Worker", gender: "Male only", age: "18+", salary: "€782 – €952/month | €4.89–€5.95/hr", note: "22 vacancies. 8 hrs/day, 5–6 days/week." },
      { title: "Food Processing Worker", gender: "Male & Female", age: "18+", salary: "€754 – €839/month | €4.71–€5.24/hr", note: "15 vacancies. 8 hrs/day, 5–6 days/week." },
      { title: "Hotel Cleaner", gender: "Male & Female", age: "18+", salary: "€720 – €996/month | €4.50–€6.23/hr", note: "25 vacancies. 8 hrs/day, 6 days/week." },
      { title: "Kitchen Helper", gender: "Male & Female", age: "18+", salary: "€750 – €896/month | €4.69–€5.60/hr", note: "34 vacancies. 8 hrs/day, 6 days/week." },
      { title: "Painter", gender: "Male only", age: "18+", salary: "€896 – €924/month | €5.60–€5.78/hr", note: "10 vacancies. 8 hrs/day, 6 days/week." },
      { title: "Packaging Assistant", gender: "Male & Female", age: "18+", salary: "€711 – €800/month | €4.44–€5.00/hr", note: "30 vacancies. 8 hrs/day, 5–6 days/week." },
    ],
    salaryTable: [
      { hours: "Construction Worker", monthly: "€782 – €952", annual: "€4.89 – €5.95/hr" },
      { hours: "Food Processing Worker", monthly: "€754 – €839", annual: "€4.71 – €5.24/hr" },
      { hours: "Hotel Cleaner", monthly: "€720 – €996", annual: "€4.50 – €6.23/hr" },
      { hours: "Kitchen Helper", monthly: "€750 – €896", annual: "€4.69 – €5.60/hr" },
      { hours: "Painter", monthly: "€896 – €924", annual: "€5.60 – €5.78/hr" },
      { hours: "Packaging Assistant", monthly: "€711 – €800", annual: "€4.44 – €5.00/hr" },
    ],
    requirements: [
      "Valid passport (personal data page and all relevant pages)",
      "Educational qualifications or professional certificates related to the applied role",
      "Work experience certificate or reference letter from previous employer (if applicable)",
      "English language proficiency — B1 level may be required for certain positions",
      "CV in European format",
      "Medical fitness certificate (mandatory for all selected candidates)",
    ],
    permitTypes: [
      { type: "Personal Work Permit", for: "Permanent residents and refugees (open employment)" },
      { type: "Employment Permit", for: "Specific employer and specific position" },
      { type: "Exceptional Cases Permit", for: "Intra-company transfers, independent professionals, trainees" },
      { type: "Self-Employment Permit", for: "Starting your own business in Serbia" },
    ],
    workProcess: [
      "Document Verification: Checking and validating applicant documents — 20–25 working days",
      "Visa Application: Submission and processing of visa requirements — 25–30 working days",
      "Approval & Work Permit: Review and approval by authorities — 40–45 working days",
      "Pre-departure Training: Orientation and safety preparation — 8–12 working days",
      "Travel & Deployment: Final travel arrangements & deployment — 10–12 working days",
    ],
    accommodation: "Free accommodation. Shared rooms. No family, partners, or pets.",
    eligibleNationalities: ["All nationalities except Somalia, Iraq, Iran, Cuba, Libya, Syria (ages 18–45)"],
    important: "Employment Contract: Minimum 2 years (renewable). Working Hours: 40–48 hours per week as per Serbia labor laws. Probation Period: 3 months. Embassy fees, travel insurance, and DHL courier fees are NOT included and must be paid directly by the applicant.",
  },

  /* ─────────────────────────────────────────
     14. SLOVAKIA
  ───────────────────────────────────────── */
  {
    id: "slovakia",
    country: "Slovakia",
    
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "Approximately 105–162 working days (4–6 months)",
    salary: "€850 – €1,300/month depending on role",
    workHours: "40 hours per week (8–10 hrs/day, 5–6 days/week)",
    benefits: [
      "Shared or subsidized accommodation (availability depends on employer)",
      "Workplace transportation or transport allowance",
      "Mandatory public health insurance coverage",
      "Occupational accident and workplace insurance",
      "Meal allowance or employer-provided meals (role dependent)",
      "Personal Protective Equipment (PPE) for industrial roles",
      "Minimum 20 paid annual leave days per year",
      "Paid sick leave according to Slovak social security law",
      "Safe working conditions in compliance with EU safety standards",
      "Initial travel assistance where applicable",
    ],
    whyChoose: [
      "Slovakia is a growing EU economy with strong demand in construction, manufacturing, and logistics.",
      "All positions comply with Slovak labor market standards and EU safety requirements.",
      "Minimum 20 paid annual leave days per year guaranteed.",
      "Overtime compensated at 125%–150% of standard hourly wage.",
      "SNJ GlobalRoutes provides complete end-to-end support.",
    ],
    inDemandJobs: [
      { title: "Plumber", gender: "Male only", age: "18+", salary: "€1,000 – €1,250/month | €5.8–€7.2/hr", note: "5 days/week, project-based." },
      { title: "Electrician", gender: "Male only", age: "18+", salary: "€950 – €1,200/month | €5.5–€6.9/hr", note: "5 days/week, overtime possible." },
      { title: "Construction Worker", gender: "Male only", age: "18+", salary: "€900 – €1,200/month | €5.2–€6.9/hr", note: "5–6 days/week." },
      { title: "Packing Worker", gender: "Male & Female", age: "18+", salary: "€850 – €1,050/month | €4.9–€6.1/hr", note: "Shift-based work." },
      { title: "Frame Worker", gender: "Male only", age: "18+", salary: "€950 – €1,300/month | €5.5–€7.5/hr", note: "Industrial environment. 10 hrs/day." },
      { title: "Warehouse Worker", gender: "Male & Female", age: "18+", salary: "€900 – €1,100/month | €5.2–€6.3/hr", note: "Shift or route-based work." },
    ],
    salaryTable: [
      { hours: "Plumber", monthly: "€1,000 – €1,250", annual: "€5.8 – €7.2/hr" },
      { hours: "Electrician", monthly: "€950 – €1,200", annual: "€5.5 – €6.9/hr" },
      { hours: "Construction Worker", monthly: "€900 – €1,200", annual: "€5.2 – €6.9/hr" },
      { hours: "Packing Worker", monthly: "€850 – €1,050", annual: "€4.9 – €6.1/hr" },
      { hours: "Frame Worker", monthly: "€950 – €1,300", annual: "€5.5 – €7.5/hr" },
      { hours: "Warehouse Worker", monthly: "€900 – €1,100", annual: "€5.2 – €6.3/hr" },
    ],
    requirements: [
      "Valid passport",
      "CV in European format",
      "Work experience certificate (role-dependent)",
      "Educational qualifications / professional certifications",
      "Police Clearance Certificate",
      "Medical Fitness Certificate (mandatory prior to visa issuance)",
    ],
    permitTypes: [
      { type: "Standard Work Permit", for: "Contract-based employment with Slovak employer" },
      { type: "Skilled Worker Permit", for: "Plumbers, electricians, frame workers" },
      { type: "Seasonal Work Permit", for: "Packing, agriculture, tourism" },
      { type: "EU Blue Card", for: "Highly qualified professionals" },
    ],
    workProcess: [
      "Document Verification: Candidate screening and validation — 10–15 working days",
      "Employer Submission: Job offer submission to Slovak authorities — 10–20 working days",
      "Work Permit Processing: Review by Ministry of Interior — 60–90 days",
      "Residence Permit Decision: Biometrics and final approval — 15–20 days",
      "Pre-Departure Preparation: Training and travel arrangement — 5–7 days",
      "Deployment: Flight and onboarding — 5–10 days",
    ],
    accommodation: "Shared or subsidized accommodation. Availability depends on employer. No family, partners, or pets.",
    eligibleNationalities: ["All nationalities — contact us for eligibility confirmation"],
    important: "Working Hours: Approximately 40 hours per week. Overtime Payment: 125%–150% of standard hourly wage. Probation Period: 3–6 months. Salary levels follow statutory minimum wage regulations and industry standards.",
  },

  /* ─────────────────────────────────────────
     15. SWEDEN
  ───────────────────────────────────────── */
  {
    id: "sweden",
    country: "Sweden",
    
    region: "Europe",
    visaType: "Sticker Visa",
    category: "Work Permit",
    processingTime: "115–205 working days (approximately 4–7 months)",
    salary: "€1,944 – €2,592/month depending on role (1 SEK ≈ 0.081 EUR)",
    workHours: "40 hours/week as per Swedish Working Hours Act (~8 hrs/day)",
    benefits: [
      "Free shared accommodation (may vary by employer and location)",
      "Transportation to and from the workplace (some employers provide, others may offer allowance)",
      "Health insurance via Försäkringskassan per Swedish Employment Law",
      "Food allowance / meals (provided for some roles; may depend on shift or company policy)",
      "Personal protective equipment (PPE) for industrial roles",
      "Paid annual leave — minimum 25 days/year per Swedish Annual Leave Act",
      "Sick leave benefits via Försäkringskassan",
      "Safe and compliant working environment following Swedish Work Environment Authority (Arbetsmiljöverket) regulations",
    ],
    whyChoose: [
      "Sweden offers among the highest wages in Europe — €1,944–€2,592/month even for non-skilled roles.",
      "Minimum 25 paid leave days per year guaranteed by Swedish Annual Leave Act.",
      "Sick leave covered by Försäkringskassan — Sweden's national social insurance system.",
      "Swedish labor contracts follow collective bargaining agreement (CBA) standards.",
      "One of the world's best quality of life standards with strong worker protections.",
    ],
    inDemandJobs: [
      { title: "Packaging / Warehouse Worker", gender: "Male & Female", age: "18+", salary: "€2,025 – €2,430/month | €11.7–€14.2/hr", note: "5 days/week, shift work common. ~8 hrs/day." },
      { title: "Store Keeper / Retail Worker", gender: "Male & Female", age: "18+", salary: "€1,944 – €2,349/month | €11.3–€13.8/hr", note: "5–6 days/week depending on store." },
      { title: "Delivery Driver (parcel / goods)", gender: "Male only", age: "18+", salary: "€2,106 – €2,592/month | €12.2–€15.0/hr", note: "5 days/week or shift-based." },
      { title: "Caregiver / Home-care Worker", gender: "Male & Female", age: "18+", salary: "€1,944 – €2,268/month | €11.3–€13.4/hr", note: "5–6 days/week, shifts possible." },
    ],
    salaryTable: [
      { hours: "Packaging / Warehouse Worker", monthly: "€2,025 – €2,430", annual: "€11.7 – €14.2/hr" },
      { hours: "Store Keeper / Retail Worker", monthly: "€1,944 – €2,349", annual: "€11.3 – €13.8/hr" },
      { hours: "Delivery Driver (parcel / goods)", monthly: "€2,106 – €2,592", annual: "€12.2 – €15.0/hr" },
      { hours: "Caregiver / Home-care Worker", monthly: "€1,944 – €2,268", annual: "€11.3 – €13.4/hr" },
    ],
    requirements: [
      "Valid passport (personal data page scan)",
      "CV in European format",
      "Work experience certificate (role-dependent, minimum 1 year preferred)",
      "Educational qualifications",
      "Police Clearance Certificate",
      "Medical Fitness Certificate (mandatory prior to visa and deployment)",
    ],
    permitTypes: [
      { type: "Standard Work Permit (Sweden)", for: "Submitted via Swedish Migration Agency (Migrationsverket)" },
      { type: "Skilled Worker Permit", for: "Drivers, caregivers, specialists" },
      { type: "Seasonal Work Permit", for: "Packing, agriculture, retail" },
      { type: "EU Blue Card", for: "Highly qualified professionals" },
    ],
    workProcess: [
      "Document Verification: Screening and validating applicant documents — 15–20 working days",
      "Employer Submission: Job offer & contract submission to Swedish Migration Agency (Migrationsverket) — 15–25 working days",
      "Work Permit Processing: Review by Swedish Migration Agency — 60–120 working days",
      "Residence Permit Decision: Biometrics & approval notification — 10–20 working days",
      "Pre-Departure Training: Orientation, safety & Swedish culture briefing — 7–10 working days",
      "Travel & Deployment: Travel arrangement and final deployment — 8–12 working days",
    ],
    accommodation: "Free shared accommodation (may vary by employer and location). No family, partners, or pets.",
    eligibleNationalities: ["All nationalities — contact us for eligibility confirmation"],
    important: "Employment Contract: Minimum 2 years (renewable). Probation Period: 6 months (common standard in Sweden). Overtime paid at legally approved rates. Swedish labor contracts follow collective bargaining agreement (CBA) standards.",
  },
];